version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/*'
    schedule: { interval: daily }
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    reviewers: ['OffchainLabs/full-stack']
    labels: ['dependencies']

    groups:
      internal:
        patterns: ['@arbitrum/*', '@offchainlabs/*']
      external-security:
        exclude-patterns: ['@arbitrum/*', '@offchainlabs/*']
        applies-to: security-updates