/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ArbOwnerPublicInterface extends utils.Interface {
  contractName: "ArbOwnerPublic";
  functions: {
    "getAllChainOwners()": FunctionFragment;
    "getInfraFeeAccount()": FunctionFragment;
    "getNetworkFeeAccount()": FunctionFragment;
    "isChainOwner(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAllChainOwners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInfraFeeAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkFeeAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isChainOwner",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllChainOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInfraFeeAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkFeeAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChainOwner",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ArbOwnerPublic extends BaseContract {
  contractName: "ArbOwnerPublic";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArbOwnerPublicInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAllChainOwners(overrides?: CallOverrides): Promise<[string[]]>;

    getInfraFeeAccount(overrides?: CallOverrides): Promise<[string]>;

    getNetworkFeeAccount(overrides?: CallOverrides): Promise<[string]>;

    isChainOwner(addr: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  getAllChainOwners(overrides?: CallOverrides): Promise<string[]>;

  getInfraFeeAccount(overrides?: CallOverrides): Promise<string>;

  getNetworkFeeAccount(overrides?: CallOverrides): Promise<string>;

  isChainOwner(addr: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getAllChainOwners(overrides?: CallOverrides): Promise<string[]>;

    getInfraFeeAccount(overrides?: CallOverrides): Promise<string>;

    getNetworkFeeAccount(overrides?: CallOverrides): Promise<string>;

    isChainOwner(addr: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getAllChainOwners(overrides?: CallOverrides): Promise<BigNumber>;

    getInfraFeeAccount(overrides?: CallOverrides): Promise<BigNumber>;

    getNetworkFeeAccount(overrides?: CallOverrides): Promise<BigNumber>;

    isChainOwner(addr: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAllChainOwners(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInfraFeeAccount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNetworkFeeAccount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isChainOwner(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
