name: Run Nitro Test Node
description: 'Checks out the Nitro repository and runs the local test node'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: OffchainLabs/nitro
        submodules: 'recursive'
        path: 'nitro'
        # TODO: Update with a stable ref once available
        ref: 'test-node-prod'

    - name: Wait for nitro startup
      shell: bash
      # The reason for the "&" at the end is https://stackoverflow.com/a/72203688
      run: ./waitForNitro.sh &

    - name: Start background nitro test-node.bash
      shell: bash
      run: cd nitro && ./test-node.bash --init --no-blockscout
