name: Run Nitro Test Node
description: 'Checks out the Nitro repository and runs the local test node'
runs:
  using: 'composite'
  steps:
    - name: Checkout Nitro
      uses: actions/checkout@v3
      with:
        repository: OffchainLabs/nitro
        submodules: 'recursive'
        path: 'nitro'
        # TODO: Update with a stable ref once available
        ref: 'test-node-prod'

    - name: Start background nitro test-node.bash
      shell: bash
      run: |
        cd nitro
        ./test-node.bash --init --no-blockscout

    - name: Copy .env
      shell: bash
      run: |
        cd sdk
        cp ./.env-sample ./.env

    - name: Wait for nitro startup
      shell: bash
      run: |
        cd sdk/scripts
        ./waitForNitro.sh
