name: Restore Cache
description: "Check out repository and restore 'node_modules' from cache"
runs:
  using: 'composite'
  steps:
    - name: Restore "node_modules" from cache
      uses: martijnhols/actions-cache/restore@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        # Fail when the cache could not be found (this should never happen unless you have a misconfiguration)
        required: true
