/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IL2Forwarder {
  export type L2ForwarderParamsStruct = {
    owner: string;
    l2Token: string;
    l3FeeTokenL2Addr: string;
    routerOrInbox: string;
    to: string;
    gasLimit: BigNumberish;
    gasPriceBid: BigNumberish;
    maxSubmissionCost: BigNumberish;
  };

  export type L2ForwarderParamsStructOutput = [
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    owner: string;
    l2Token: string;
    l3FeeTokenL2Addr: string;
    routerOrInbox: string;
    to: string;
    gasLimit: BigNumber;
    gasPriceBid: BigNumber;
    maxSubmissionCost: BigNumber;
  };
}

export interface IL2ForwarderFactoryInterface extends utils.Interface {
  contractName: "IL2ForwarderFactory";
  functions: {
    "aliasedL1Teleporter()": FunctionFragment;
    "callForwarder((address,address,address,address,address,uint256,uint256,uint256))": FunctionFragment;
    "createL2Forwarder(address,address,address)": FunctionFragment;
    "l2ForwarderAddress(address,address,address)": FunctionFragment;
    "l2ForwarderFactory()": FunctionFragment;
    "l2ForwarderImplementation()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aliasedL1Teleporter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callForwarder",
    values: [IL2Forwarder.L2ForwarderParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createL2Forwarder",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "l2ForwarderAddress",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "l2ForwarderFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "l2ForwarderImplementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "aliasedL1Teleporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createL2Forwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2ForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2ForwarderFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2ForwarderImplementation",
    data: BytesLike
  ): Result;

  events: {
    "CalledL2Forwarder(address,tuple)": EventFragment;
    "CreatedL2Forwarder(address,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CalledL2Forwarder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatedL2Forwarder"): EventFragment;
}

export type CalledL2ForwarderEvent = TypedEvent<
  [string, IL2Forwarder.L2ForwarderParamsStructOutput],
  { l2Forwarder: string; params: IL2Forwarder.L2ForwarderParamsStructOutput }
>;

export type CalledL2ForwarderEventFilter =
  TypedEventFilter<CalledL2ForwarderEvent>;

export type CreatedL2ForwarderEvent = TypedEvent<
  [string, string, string, string],
  { l2Forwarder: string; owner: string; routerOrInbox: string; to: string }
>;

export type CreatedL2ForwarderEventFilter =
  TypedEventFilter<CreatedL2ForwarderEvent>;

export interface IL2ForwarderFactory extends BaseContract {
  contractName: "IL2ForwarderFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IL2ForwarderFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aliasedL1Teleporter(overrides?: CallOverrides): Promise<[string]>;

    callForwarder(
      params: IL2Forwarder.L2ForwarderParamsStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createL2Forwarder(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    l2ForwarderAddress(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    l2ForwarderFactory(overrides?: CallOverrides): Promise<[string]>;

    l2ForwarderImplementation(overrides?: CallOverrides): Promise<[string]>;
  };

  aliasedL1Teleporter(overrides?: CallOverrides): Promise<string>;

  callForwarder(
    params: IL2Forwarder.L2ForwarderParamsStruct,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createL2Forwarder(
    owner: string,
    routerOrInbox: string,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  l2ForwarderAddress(
    owner: string,
    routerOrInbox: string,
    to: string,
    overrides?: CallOverrides
  ): Promise<string>;

  l2ForwarderFactory(overrides?: CallOverrides): Promise<string>;

  l2ForwarderImplementation(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    aliasedL1Teleporter(overrides?: CallOverrides): Promise<string>;

    callForwarder(
      params: IL2Forwarder.L2ForwarderParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createL2Forwarder(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<string>;

    l2ForwarderAddress(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<string>;

    l2ForwarderFactory(overrides?: CallOverrides): Promise<string>;

    l2ForwarderImplementation(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CalledL2Forwarder(address,tuple)"(
      l2Forwarder?: string | null,
      params?: null
    ): CalledL2ForwarderEventFilter;
    CalledL2Forwarder(
      l2Forwarder?: string | null,
      params?: null
    ): CalledL2ForwarderEventFilter;

    "CreatedL2Forwarder(address,address,address,address)"(
      l2Forwarder?: string | null,
      owner?: string | null,
      routerOrInbox?: null,
      to?: null
    ): CreatedL2ForwarderEventFilter;
    CreatedL2Forwarder(
      l2Forwarder?: string | null,
      owner?: string | null,
      routerOrInbox?: null,
      to?: null
    ): CreatedL2ForwarderEventFilter;
  };

  estimateGas: {
    aliasedL1Teleporter(overrides?: CallOverrides): Promise<BigNumber>;

    callForwarder(
      params: IL2Forwarder.L2ForwarderParamsStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createL2Forwarder(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    l2ForwarderAddress(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2ForwarderFactory(overrides?: CallOverrides): Promise<BigNumber>;

    l2ForwarderImplementation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    aliasedL1Teleporter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    callForwarder(
      params: IL2Forwarder.L2ForwarderParamsStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createL2Forwarder(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    l2ForwarderAddress(
      owner: string,
      routerOrInbox: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2ForwarderFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2ForwarderImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
