name: Build and lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check cache for "node_modules"
        id: cache
        uses: martijnhols/actions-cache/check@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Save "node_modules" to cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: martijnhols/actions-cache/save@v3
        with:
          path: "**/node_modules"
          key: ${{ steps.cache.outputs.primary-key }}

  sdk:
    name: Lint SDK
    runs-on: ubuntu-latest
    needs: install
    env:
      TEST_PATH: /tmp/test-results
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache

      - name: Lint sdk
        run: |
          yarn gen:abi
          yarn build --reporter-options output=$TEST_PATH/sdk.xml
          yarn lint --format junit -o $TEST_PATH/sdk-lint.xml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: ${{ env.TEST_PATH }}
    
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '${{ env.TEST_PATH }}/sdk-lint.xml'
          fail_on_failure: false

      # TODO: need to fix codecov, hasn't been working for a while according to #172 comment
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: false

  sdk-audit:
    name: Audit SDK
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache

      - run: yarn audit:ci
